# AI Seminar Practical Test

**Συμπληρώστε παρακάτω τα στοιχεία σας:**

**Επώνυμο:** Αγγλογάλλος 

**Όνομα:** Αναστάσιος

**Σχολή:** ΗΜΜΥ

**Α.Μ.:** 03118641



### Ζητούμενα - Οδηγίες
Καλείστε να χρησιμοποιήσετε τη μέθοδο **(Gaussian) Naive Bayes** της Python scikit-learn για την ταξινόμηση της προέλευσης του κρασιού με βάση τη φυσικοχημική δεδομένα ανάλυσης. Θα χρησιμοποιήσετε το Wine Data Set του UCI Machine Learning Repository. Αυτά τα δεδομένα είναι τα αποτελέσματα μιας χημικής ανάλυσης κρασιών που καλλιεργούνται στην ίδια περιοχή στην Ιταλία αλλά προέρχονται από τρεις διαφορετικές ποικιλίες. Η ανάλυση προσδιόρισε τις ποσότητες 13 συστατικών που βρέθηκαν σε καθένα από τα τρία είδη κρασιών. Μπορείτε να βρείτε λεπτομέρειες [εδώ](http://archive.ics.uci.edu/ml/datasets/Wine).

Kατεβάστε το dataset από [εδώ](https://drive.google.com/file/d/1OKzRlTnmJavmXBJjRhUZO_VA-u_dqylN/view?usp=share_link)

Χρησιμοποιήστε όλα τα (13) χαρακτηριστικά για να κάνετε την ταξινόμηση. Χωρίστε τα training & test sets με αναλογία της επιλογής σας, αιτιολογώντας την με συντομία. 
Θα πρέπει να εμφανίσετε σε πίνακες τα εξής αποτελέσματα:
- accuracy, precision, recall, f1-score (α) ανά κλάση και (β) συνολικά.
- confusion matrix

Για οποιοδήποτε βήμα δεν δίνεται συγκεκριμένη οδηγία (επιλογή παραμέτρων, προεπεξεργασία δεδομένων, κ.λπ.) έχετε την ελευθερία επιλογής, παραθέτοντας μια σύντομη εξήγηση της επιλογής σας.

Θα πρέπει να ανεβάσετε το notebook σας στο helios στο σημείο που θα σας υποδειχθεί.
**Πριν το ανεβάσετε, βεβαιωθείτε ότι έχετε τρέξει όλα τα κελιά κώδικα που υπάρχουν στο notebook σας.**

Καλή επιτυχία!



Αρχικά κάνουμε import τις απαραίτητες βιβλιοθήκες και έπειτα κάνουμε load το dataset

In [1]:
# Libraries
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# Load dataset
url = "https://drive.google.com/file/d/1OKzRlTnmJavmXBJjRhUZO_VA-u_dqylN/view"
file_id = url.split('/')[-2]
dwn_url = 'https://drive.google.com/uc?id=' + file_id
wine = pd.read_csv(dwn_url)


Σε αυτό το σημείο θα διαχωρίσουμε τα δεδομένα σε δεδομένα προς εκπαίδευση και δεδομένα για την αξιολόγηση του μοντέλου μας. Θα κάνουμε διαχωρισμό 70 / 30 όπως κάναμε και στο μάθημα των Νευρωνικών Δικτύων. Θα μπορούσαμε να διαλέξουμε και άλλο νούμερο , η μόνη προυπόθεση το train set να είναι σημαντικά μεγαλύτερο από το train set.

In [2]:
# Split data into a train set (70%) and a test set (30%)
X = wine.iloc[:, 1:].values
y = wine.iloc[:, 0].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)


Αρχικοιποιούμε ένα GNB classifier και έπειτα τον εκπαιδεύουμε στο train set 

In [3]:
# Initialise GNB classifier
clf = GaussianNB()

# Train clf on the training set
clf.fit(X_train, y_train)

GaussianNB()

Τέλος βάζουμε τον classifier που έχουμε εκπαιδεύσει να προβλέψει την κατηγοριοποίηση των δεδομένων του test set. Έπειτα κοιτάμε στο report τα ζητούμενα : 

In [5]:
# Predict the test set's classification
y_pred = clf.predict(X_test)

# Performance Report
print(classification_report(y_test, y_pred))
# Total Accuracy
print("Accuracy:", clf.score(X_test, y_test))
# Confusion Matrix
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.90      1.00      0.95        19
           2       1.00      0.86      0.93        22
           3       0.93      1.00      0.96        13

    accuracy                           0.94        54
   macro avg       0.94      0.95      0.95        54
weighted avg       0.95      0.94      0.94        54

Accuracy: 0.9444444444444444

Confusion Matrix:
 [[19  0  0]
 [ 2 19  1]
 [ 0  0 13]]


Παρατηρούμε ότι ο ταξινομητής κατεφέρνει να έχει accuracy 0.955 το οποίο είναι αρκετά υψηλό. Τo precission, recall και το f1-score για κάθε κλάση είναι επίση υψηλό το οποίο σημαίνει ότι ο gnb συμπεριφέρετε καλά σε κάθε κλάση. 



Γνωρίζουμε ότι ο GNB ταξινομητής δουλεύει σωστά και βγάζει υψηλά αποτελέσματα όταν τα δεδομένα έχουν Gaussian κατανομή. Οπότε μπορούμε να υποθέσουμε πως το ίδιο γίνεται και στην περιπτωσή μας.